/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bank;

import java.awt.event.*;
import java.awt.*;
import java.io.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author Kevin
 */
public class BankSystem extends javax.swing.JFrame {
    ArrayList<ArrayList<String>> accounts=new ArrayList<>();
    String accountNumber;
    String pin;
    Thread hook=new Thread(){
        @Override
        public void run(){
            try{
                PrintWriter temp=new PrintWriter("AccountData.txt");
                for(int i=0;i<accounts.size();i++){
                    for(int j=0;j<accounts.get(i).size();j++){
                        temp.write(accounts.get(i).get(j)+"//");
                    }
                    temp.println();
                }
                temp.close();
            }catch(Exception e){}
        }
    };
   
    /**
     * Creates new form BankSystem
     */
    public BankSystem() {
        initComponents();
        getData();
        setResizable(false);
        pack();
        setLocationRelativeTo(null);
        Runtime.getRuntime().addShutdownHook(hook);
    }
    
    private void getData(){
        try{
            Scanner in=new Scanner(new FileInputStream("AccountData.txt")).useDelimiter("\n");
            while(in.hasNext()){
                ArrayList<String> temp=new ArrayList<>();
                String next=in.next().trim();
                Scanner inner=new Scanner(next).useDelimiter("//");
                while(inner.hasNext()){
                    String Inner=inner.next().trim();
                    temp.add(Inner);
                }
                accounts.add(temp);
            }
        }catch(FileNotFoundException fnfe){}
    }
    
    private void setData(){
        for(int i=0;i<accounts.size();i++){
            if(accounts.get(i).get(0).equalsIgnoreCase(accountNumber)){
                txtAcc.setText(accounts.get(i).get(0));
                txtNm.setText(accounts.get(i).get(1));
                txtType.setText(accounts.get(i).get(2));
                txtBalance.setText(accounts.get(i).get(3));
                comboStatus.setSelectedItem(txtType.getText());
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameCreate = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btncreate = new javax.swing.JButton();
        txtAccountNumber = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtpin = new javax.swing.JPasswordField();
        txtpin2 = new javax.swing.JPasswordField();
        comboType = new javax.swing.JComboBox<>();
        frameStatus = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtAcc = new javax.swing.JTextField();
        txtNm = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();
        txtTransaction = new javax.swing.JTextField();
        comboStatus = new javax.swing.JComboBox<>();
        btnDeposit = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAccount = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        txtPin = new javax.swing.JPasswordField();

        frameCreate.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        frameCreate.setResizable(false);
        frameCreate.setSize(new java.awt.Dimension(400, 325));

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 3, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CREATE ACCOUNT");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel5.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Acc. Number");

        jLabel6.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Name");

        jLabel7.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Acc. Type");

        jLabel8.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Pin");

        jLabel9.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Repeat Pin");

        btncreate.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btncreate.setText("CREATE");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });
        btncreate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btncreateKeyReleased(evt);
            }
        });

        txtAccountNumber.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        txtAccountNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btncreateKeyReleased(evt);
            }
        });

        txtName.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btncreateKeyReleased(evt);
            }
        });

        txtpin.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        txtpin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btncreateKeyReleased(evt);
            }
        });

        txtpin2.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        txtpin2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btncreateKeyReleased(evt);
            }
        });

        comboType.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        comboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Business", "Personal", "Other" }));
        comboType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btncreateKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout frameCreateLayout = new javax.swing.GroupLayout(frameCreate.getContentPane());
        frameCreate.getContentPane().setLayout(frameCreateLayout);
        frameCreateLayout.setHorizontalGroup(
            frameCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameCreateLayout.createSequentialGroup()
                .addGroup(frameCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameCreateLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameCreateLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameCreateLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameCreateLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameCreateLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtpin, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameCreateLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtpin2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameCreateLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btncreate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frameCreateLayout.setVerticalGroup(
            frameCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameCreateLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(frameCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frameCreateLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frameCreateLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(frameCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameCreateLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(frameCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frameCreateLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(frameCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frameCreateLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtpin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btncreate)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        frameStatus.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setFont(new java.awt.Font("Kristen ITC", 3, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("STATUS CHECK");

        jLabel11.setFont(new java.awt.Font("Courier New", 3, 11)); // NOI18N
        jLabel11.setText("Acc. No");

        jLabel12.setFont(new java.awt.Font("Courier New", 3, 11)); // NOI18N
        jLabel12.setText("Name");

        jLabel13.setFont(new java.awt.Font("Courier New", 3, 11)); // NOI18N
        jLabel13.setText("Type");

        jLabel14.setFont(new java.awt.Font("Courier New", 3, 11)); // NOI18N
        jLabel14.setText("Balance");

        jLabel15.setFont(new java.awt.Font("Courier New", 3, 11)); // NOI18N
        jLabel15.setText("Transaction");

        jLabel16.setFont(new java.awt.Font("Courier New", 3, 11)); // NOI18N
        jLabel16.setText("Change Type");

        txtAcc.setEditable(false);
        txtAcc.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        txtAcc.setForeground(new java.awt.Color(0, 0, 0));
        txtAcc.setFocusable(false);

        txtNm.setEditable(false);
        txtNm.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        txtNm.setForeground(new java.awt.Color(0, 0, 0));
        txtNm.setFocusable(false);

        txtType.setEditable(false);
        txtType.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        txtType.setForeground(new java.awt.Color(0, 0, 0));
        txtType.setFocusable(false);

        txtBalance.setEditable(false);
        txtBalance.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        txtBalance.setForeground(new java.awt.Color(0, 0, 0));
        txtBalance.setFocusable(false);

        txtTransaction.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N

        comboStatus.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Business", "Personal", "Other" }));
        comboStatus.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboStatusPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        btnDeposit.setText("Deposit");
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });
        btnDeposit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnDepositKeyReleased(evt);
            }
        });

        btnWithdraw.setText("Withdraw");
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });
        btnWithdraw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnDepositKeyReleased(evt);
            }
        });

        btnBack.setText("Log Out");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        btnBack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnBackKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout frameStatusLayout = new javax.swing.GroupLayout(frameStatus.getContentPane());
        frameStatus.getContentPane().setLayout(frameStatusLayout);
        frameStatusLayout.setHorizontalGroup(
            frameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(frameStatusLayout.createSequentialGroup()
                        .addGroup(frameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAcc)
                            .addComponent(txtNm)
                            .addComponent(txtType)
                            .addComponent(txtBalance)
                            .addGroup(frameStatusLayout.createSequentialGroup()
                                .addComponent(txtTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeposit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnWithdraw)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(comboStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameStatusLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        frameStatusLayout.setVerticalGroup(
            frameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(frameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeposit)
                    .addComponent(btnWithdraw))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 3, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");

        jLabel2.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        jLabel2.setText("Account Number");

        jLabel3.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        jLabel3.setText("Pin");

        txtAccount.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        txtAccount.setForeground(new java.awt.Color(0, 0, 0));
        txtAccount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnLoginKeyReleased(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        btnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnLoginKeyReleased(evt);
            }
        });

        btnCreate.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        btnCreate.setText("CREATE");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        btnCreate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnCreateKeyReleased(evt);
            }
        });

        txtPin.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        txtPin.setForeground(new java.awt.Color(0, 0, 0));
        txtPin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnLoginKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addComponent(btnCreate))
                            .addComponent(txtAccount)
                            .addComponent(txtPin))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnCreate))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        boolean viable=false;
        accountNumber=txtAccount.getText().trim();
        pin=txtPin.getText();
        for(int i=0;i<accounts.size();i++){
            if(accounts.get(i).get(0).equalsIgnoreCase(accountNumber)&&accounts.get(i).get(4).equalsIgnoreCase(pin)){
                viable=true;
                setVisible(false);
                setData();
                frameStatus.setResizable(false);
                frameStatus.pack();
                frameStatus.setLocationRelativeTo(null);
                frameStatus.setVisible(true);
            }
        }
        if(!viable){
            JOptionPane.showMessageDialog(null,"Login Unsuccessful\nInvalid Credentials","Error",JOptionPane.ERROR_MESSAGE);
            txtAccount.setText("");
            txtPin.setText("");
            txtAccount.requestFocus();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            btnLogin.doClick();
        }else if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            System.exit(0);
        }
    }//GEN-LAST:event_btnLoginKeyReleased

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        try{    
            String account=txtAccountNumber.getText().trim();
            String name=txtName.getText().trim();
            String type=comboType.getSelectedItem().toString();
            String Pin=txtpin.getText();
            String Pin2=txtpin2.getText();
            if(name.isEmpty()||type.isEmpty()||Pin.isEmpty()||Pin2.isEmpty()){
                JOptionPane.showMessageDialog(null,"A required field is empty","Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
            Integer.parseInt(Pin);
            Integer.parseInt(Pin2);
            for(int i=0;i<accounts.size();i++){
                if(account.equals(accounts.get(i).get(0))){
                    JOptionPane.showMessageDialog(null,"Account Number already in use.","Error",JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            if(account.isEmpty()){
                account=String.valueOf(Integer.parseInt(accounts.get(0).get(0))+1);
                for(int i=1;i<accounts.size();i++){
                    if(accounts.get(i).get(0).compareToIgnoreCase(account)>=0){
                        account=String.valueOf(Integer.parseInt(accounts.get(i).get(0))+1);
                    }
                }
                JOptionPane.showMessageDialog(null,"Your Account Number is"+account,"Information",JOptionPane.INFORMATION_MESSAGE);
            }
            if(account.length()!=6 && !txtAccountNumber.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Account Number must be 6 digits","Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(!Pin.equals(Pin2)){
                JOptionPane.showMessageDialog(null,"Pins do not match","Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
            Integer.parseInt(account);
            ArrayList<String> temp=new ArrayList<>();
            temp.add(account);
            temp.add(name);
            temp.add(type);
            temp.add("0");
            temp.add(Pin);
            accounts.add(temp);
            frameCreate.setVisible(false);
            setVisible(true);
            txtAccount.setText(account);
            txtPin.requestFocus();
            txtAccountNumber.setText("");
            txtName.setText("");
            txtpin.setText("");
            txtpin2.setText("");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Account Number and Pin Number have to be numbers!!","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btncreateActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        setVisible(false);
        frameCreate.setLocationRelativeTo(null);
        frameCreate.setVisible(true);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnCreateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCreateKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            btnCreate.doClick();
        }else if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            System.exit(0);
        }
    }//GEN-LAST:event_btnCreateKeyReleased

    private void btncreateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btncreateKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            btncreate.doClick();
        }else if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            System.exit(0);
        }
    }//GEN-LAST:event_btncreateKeyReleased

    private void comboStatusPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboStatusPopupMenuWillBecomeInvisible
        String type=comboStatus.getSelectedItem().toString();
        for(int i=0;i<accounts.size();i++){
            if(accounts.get(i).get(0).equalsIgnoreCase(accountNumber)){
                accounts.get(i).set(2,type);
                setData();
            }
        }
    }//GEN-LAST:event_comboStatusPopupMenuWillBecomeInvisible

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        if(evt.getSource().equals(btnDeposit)){
            String amount=txtTransaction.getText().trim();
            try{
                for(int i=0;i<accounts.size();i++){
                    if(accounts.get(i).get(0).equalsIgnoreCase(accountNumber)){
                        int before=Integer.parseInt(accounts.get(i).get(3));
                        int add=Integer.parseInt(amount);
                        int balance=before+add;
                        accounts.get(i).set(3,String.valueOf(balance));
                        setData();
                        txtTransaction.setText("");
                    }
                }
            }catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(null,"Use Numbers for Transactions","Error",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            String amount=txtTransaction.getText().trim();
            try{
                for(int i=0;i<accounts.size();i++){
                    if(accounts.get(i).get(0).equalsIgnoreCase(accountNumber)){
                        int before=Integer.parseInt(accounts.get(i).get(3));
                        int deduct=Integer.parseInt(amount);
                        int balance=before-deduct;
                        if(balance<0){
                            JOptionPane.showMessageDialog(null,"You cannot withdraw more than you have","Error",JOptionPane.ERROR_MESSAGE);
                            txtTransaction.setText("");
                            return;
                        }
                        accounts.get(i).set(3,String.valueOf(balance));
                        setData();
                        txtTransaction.setText("");
                    }
                }
            }catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(null,"Use Numbers for Transactions","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnDepositKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDepositKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            JButton temp=(JButton)evt.getSource();
            temp.doClick();
        }else if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            System.exit(0);
        }
    }//GEN-LAST:event_btnDepositKeyReleased

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        frameStatus.setVisible(false);
        txtAccount.setText("");
        txtPin.setText("");
        txtAccount.requestFocus();
        setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBackKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBackKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            JButton temp=(JButton)evt.getSource();
            temp.doClick();
        }else if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            System.exit(0);
        }
    }//GEN-LAST:event_btnBackKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JButton btncreate;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JComboBox<String> comboType;
    private javax.swing.JFrame frameCreate;
    private javax.swing.JFrame frameStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAcc;
    private javax.swing.JTextField txtAccount;
    private javax.swing.JTextField txtAccountNumber;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNm;
    private javax.swing.JPasswordField txtPin;
    private javax.swing.JTextField txtTransaction;
    private javax.swing.JTextField txtType;
    private javax.swing.JPasswordField txtpin;
    private javax.swing.JPasswordField txtpin2;
    // End of variables declaration//GEN-END:variables
}
